FROM nvidia/opengl:1.0-glvnd-runtime-centos7

ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES},graphics,compat32

RUN yum-config-manager --add-repo https://virtualgl.org/pmwiki/uploads/Downloads/VirtualGL.repo \
 && yum -y install \
    yum-utils \
    xorg-x11-utils \
    xorg-x11-xauth \
    glx-utils \
    VirtualGL.x86_64 VirtualGL.i386 \
 && yum clean all \
 && rm -rf /etc/ld.so.cache \
 && rm -rf /var/cache/ldconfig/* \
 && rm -rf /tmp/*
