FROM ubuntu:21.04

RUN apt-get update && apt-get install -y \
  x11-apps \
  mesa-utils \
  libxtst6 \
  libxv1 \
  libglu1-mesa

COPY virtualgl_2.6.5_amd64.deb ./vgl.deb
RUN dpkg -i vgl.deb

RUN rm -rf /tmp/* /usr/share/doc/* /usr/share/info/* /var/tmp/*
# RUN useradd -ms /bin/bash user
# ENV DISPLAY :0
 
# USER user
# ENTRYPOINT ["/bin/sh", "-c", "$0 \"$@\"", "glxgears"]

CMD ["/bin/bash"]
